<template>
  <div>
    <div class="lg:container mx-auto">
        <div id="4889704610" data-spm="4889704610" data-uuid="4889704610" mod-name="lzdrwb-richtext" data-version="1.1.7" data-tracker="4889704610" trackinfo="lzdrwb-richtext.4889704610.3" data-module="lzdrwb-richtext.4889704610.3" mod-spm="a2o4m.tm80185656.4889704610" data-spm-anchor-id="a2o4m.tm80185656.4889704610.0.0" class="mui-zebra-module aplus-common-module-data-tracker" style="box-sizing: border-box; display: flex; flex-direction: column; align-content: flex-start; flex-shrink: 0; border: 0px solid black;" data-appeared="true" data-has-appeared="true" data-before-current-y="-8121.015625" data-aplus-ae="4"><div class="rule-content rule-content"><div><p style="text-align:justify;" data-spm-anchor-id="a2o4m.tm80185656.4889704610.i2.4f46B9uRB9uRG4"><span style="color: black;font-size: 10pt;font-family: Arial, sans-serif;"><strong data-spm-anchor-id="a2o4m.tm80185656.4889704610.i3.4f46B9uRB9uRG4">(Latest updated 1 September 2022)</strong></span>&nbsp;</p>
<p data-spm-anchor-id="a2o4m.tm80185656.4889704610.i0.4f46B9uRB9uRG4">Welcome to the www.lazada.co.th website and/or the LAZADA mobile app. Please read these terms and conditions carefully. The following Terms of Use govern your use and access of the Platform (defined below) and the use of the Services.</p>
<p>By accessing the Platform and/or using the Services, you agree to be bound by these Terms of Use. If you do not agree to these Terms of Use, do not access and/or use this Platform or the Services.</p>
<p>Access to and use of password protected and/or secure areas of the Platform and/or use of the Services are restricted to Customers with accounts only. You may not obtain or attempt to obtain unauthorized access to such parts of this Platform and/or Services, or to any other protected information, through any means not intentionally made available by us for your specific use. A breach of this provision may be an offence under the Computer Crime Act B.E. 2550 (2007) of Thailand.</p>
<p>If you are below 20 years old: you must obtain consent from your parent(s) or legal guardian(s), their acceptance of these Terms of Use and their agreement to take responsibility for: (i) your actions; (ii) any charges associated with your use of any of the Services or purchase of Products; and (iii) your acceptance and compliance with these Terms of Use. If you do not have consent from your parent(s) or legal guardian(s), you must stop using/accessing this Platform and using the Services.</p>
<p>1. Definitions &amp; Interpretation</p>
<p>Unless otherwise defined, the definitions and provisions in respect of interpretation set out in Schedule 1 will apply to these Terms of Use.</p>
<p>2. General use of the Services and/or access of the Platform</p>
<p>2.1 Guidelines to the use of the Platform and/or the Services: You agree to comply with any and all the guidelines, notices, operating rules and policies and instructions pertaining to the use of the Services and/or access to the Platform, as well as any amendments to the aforementioned, issued by us, from time to time. We reserve the right to revise these guidelines, notices, operating rules and policies and instructions at any time and you are deemed to be aware of and bound by any changes to the foregoing upon their publication on the Platform.</p>
<p>2.2 Restricted activities: You agree and undertake NOT to:</p>
<p>(a) impersonate any person or entity or to falsely state or otherwise misrepresent your affiliation with any person or entity;</p>
<p>(b) use the Platform or Services for illegal purposes;</p>
<p>(c) attempt to gain unauthorized access to or otherwise interfere or disrupt other computer systems or networks connected to the Platform or Services;</p>
<p>(d) post, promote or transmit through the Platform or Services any Prohibited Materials;</p>
<p>(e) interfere with another’s utilization and enjoyment of the Platform or Services;</p>
<p>(f) use or upload, in any way, any software or material that contains, or which you have reason to suspect that contains, viruses, damaging components, malicious code or harmful components which may impair or corrupt the Platform’s data or damage or interfere with the operation of another Customer’s computer or mobile device or the Platform or the Services; and</p>
<p>(g) use the Platform or the Services other than in conformance with the acceptable use policies of any connected computer networks, any applicable Internet standards and any other applicable laws.</p>
<p>(h) create and/or use more than one Customer’s and/or any Lazada user’s account on the Platform and/or the Services.</p>
<p>2.3 Availability of the Platform and the Services: We may, from time to time and without giving any reason or prior notice, upgrade, modify, suspend or discontinue the provision of or remove, whether in whole or in part, the Platform or any Services and shall not be liable if any such upgrade, modification, suspension or removal prevents you from accessing the Platform or any part of the Services.</p>
<p>2.4 Right to monitor content: We reserve the right, at its sole discretion, but shall not be obliged to:</p>
<p>(a) monitor, screen or otherwise control any activity, content or material on the Platform and/or through the Services. We may, in our sole and absolute discretion, investigate any violation of the terms and conditions contained herein and may take any action it deems appropriate;</p>
<p>(b) prevent or restrict access of any Customer to the Platform and/or the Services;</p>
<p>(c) report any activity we suspect to be in violation of any applicable law, statute or regulation to the appropriate authorities and to co-operate with such authorities; and/or</p>
<p>(d) to request any information and data from you in connection with your use of the Services and/or access of the Platform at any time and to exercise our right under this paragraph if you refuse to divulge such information and/or data or if you provide or if we have reasonable grounds to suspect that you have provided inaccurate, misleading or fraudulent information and/or data.</p>
<p>(e) deactivate, cancel, delete, ban, prevent and restrict any access to the Platform and/or the Service of and by any Lazada account, Customer and/or anyone whether permanently or temporarily and without giving any reason or prior notice.</p>
<p>2.5 Privacy Policy: Your use of the Services and/or access to the Platform is also subject to the Privacy Policy as set out at https://www.lazada.co.th/privacy-policy/</p>
<p>2.6 Terms &amp; Conditions of Sale and Voucher Terms &amp; Conditions: Purchases of any Product would be subject to the Terms &amp; Conditions of Sale as set out at https://www.lazada.co.th/terms-conditions/. If you use a Voucher, the Voucher Terms &amp; Conditions are set out at http://www.lazada.co.th/terms-conditions/#voucher would apply.</p>
<p>2.7 Additional terms: In addition to these Terms of Use, the use of specific aspects of the Materials and the Services, more comprehensive or updated versions of the Materials offered by us or our designated sub-contractors, may be subject to additional terms and conditions, which will apply in full force and effect.</p>
<p>3. Use of the Services</p>
<p>3.1 Application of this Clause: In addition to all other terms and conditions of this Terms of Use, the provisions in this Clause 3 are the additional specific terms and conditions governing your use of the Services.</p>
<p>3.2 Restrictions: Use of the Services is limited to the authorised Customers who are of legal age and have the legal capacity to enter into and form contracts under any applicable law. The Customers who have breached or are in breach of the terms and conditions contained herein and the Customers who have been permanently or temporarily suspended from using any of the Services may not use the Services even if they satisfy the requirements of this Clause 3.2.</p>
<p>3.3 General terms of use: You agree:</p>
<p>(a) to access and/or use the Services only for lawful purposes and in a lawful manner at all times and further agree to conduct any activity relating to the Services in good faith; and</p>
<p>(b) to ensure that any information or data you post or cause to appear on the Platform in connection with the Services is accurate and not violate any applicable law. You also agree to take sole responsibility for such information and data.</p>
<p>3.4 Product description: While we endeavour to provide an accurate description of the Products, we do not warrant that such description is accurate, current or free from error.</p>
<p>3.5 Prices of Products: All Listing Prices are subject to taxes, unless explicitly stated otherwise. We reserve the right to amend the Listing Prices at any time without giving any reason or prior notice.</p>
<p>3.6 Third Party Vendors: You acknowledge that parties other than Lazada (i.e. Third Party Vendors) list and sell their Products on the Platform. The information regarding whether a particular Product is listed for sale on the Platform by Lazada or a Third Party Vendor may be stated on the webpage listing that Product. For the avoidance of doubt, each agreement entered into for the sale of a Third Party Vendor’s Products to a Customer shall be an agreement entered into directly and only between the Third Party Vendor and the Customer and also subjected to the Terms and Conditions of Sale.</p>
<p>4. Customers with Lazada accounts</p>
<p>4.1 Username/Password: Certain Services that may be made available on the Platform may require creation of an account with us or for you to provide Personal Data. If you request to create an account with us, a Username and Password may either be: (i) determined and issued to you by us; or (ii) provided by you and accepted by us in our sole and absolute discretion in connection with the use of the Services and/or access to the relevant Platform. We may at any time in our sole and absolute discretion, request that you update your Personal Data or forthwith invalidate the Username and/or Password without giving any reason or prior notice and shall not be liable or responsible for any Losses suffered by or caused by you or arising out of or in connection with or by reason of such request or invalidation. You hereby agree to change your Password from time to time and to keep the Username and Password confidential and shall be responsible for the security of your account and liable for any disclosure or use (whether such use is authorized or not) of the Username and/or Password. You are to notify us immediately if you have knowledge that or have reason for suspecting that the confidentiality of the Username and/or Password has been compromised or if there has been any unauthorized use of the Username and/or Password or if your Personal Data requires updating. The notice will be deemed to be processed by us seven (7) business days after the receipt of such notice.</p>
<p>4.2 Biometric Login Service:  If your device supports fingerprint or facial recognition features, you may be able to set up these as your verification methods and use your fingerprint or face identification registered on a permitted mobile device in lieu of your Username and/or Password, or one-time pin (OTP) as a security code to confirm your identity to access the Platform and/or use of the Services (“Biometric Login”). You acknowledge and agree that in order to use the Biometric Login:</p>
<p>(a)	you must install our mobile application using a permitted mobile device. For the purposes of this Clause, a permitted mobile device shall be one that is deemed to be a “trusted device” based on the security criteria which shall be determined by Lazada at its sole discretion from time to time;</p>
<p>(b)	you will need to ensure that the fingerprint / face recognition function has been activated on your permitted mobile device and thus your face identification or fingerprint for control access has been registered and stored in your permitted mobile device;</p>
<p>(c)	you must ensure that only your face and/or fingerprint identification are stored in your permitted mobile device to access the device and you understand that upon activation of the Biometric Login function in your account, any face / fingerprint identification that is stored on your permitted mobile device will be used for purpose of the Biometric Login and to access the Platform and/or Services under your account;&nbsp;&nbsp;</p>
<p>(d)	by activating the Biometric Login function in your Account, you hereby agree and authorize Lazada to access the face / fingerprint identification function in your permitted mobile device, and you hereby consent to Lazada accessing and using such information for the provision of the Service under your account. Please note that Lazada does not collect, process or store your face/ fingerprint information in the provision of this service;&nbsp;</p>
<p>(e)	the face / fingerprint authentication module of the permitted mobile device is not provided by Lazada, and we make no representation or warranty as to the security of the Biometric Login function of any permitted mobile device and whether it works in the way that the manufacturer of the device represents;&nbsp;&nbsp;</p>
<p>(f)	unless prohibited by applicable laws from excluding or limiting our liability, Lazada is not liable for any loss you incur in connection with the use or attempted use of the Biometric Login, access to your Account by using the Biometric Login, or your instructions, or any unauthorised transactions through or in connection with the Biometric Login service; and</p>
<p>(g)	Lazada does not represent or warrant that the Biometric Login service will be accessible at all times, or function with any electronic equipment, software, infrastructure or other Services that we may offer from time to time. You may at any time still choose to access the mobile app using your Username and Password, and/or choose to deactivate the Biometric Login service at any time via your mobile application once you are signed in.</p>
<p>4.3 Purported use/access: You agree and acknowledge that any use of the Services and/or any access to the Platform and any information, data or communications referable to your Username and Password (including any access using the Biometric Login) shall be deemed to be, as the case may be:</p>
<p>(a) access to the relevant Platform and/or use of the Services by you; or</p>
<p>(b) information, data or communications posted, transmitted and validly issued by you.</p>
<p>Your Username, Password and facial or fingerprint identification are confidential information that cannot be shared with any party. We will always hold and assume that the use of your Username, Password and/or Biometric Login is done by you alone and has the right to conclude that such utilization/activity is conducted or sent by you. You further agree and acknowledge that you shall be bound by and agree to fully indemnify us against any and all Losses attributable to any use of any Services and/or or access to the Platform referable to your Username and Password (including via any face / fingerprint identification).</p>
<p>5. Intellectual property</p>
<p>5.1 Ownership: The Intellectual Property in and to the Platform and the Materials are owned, licensed to or controlled by us, our licensors or our service providers. We reserve the right to enforce the right of the Intellectual Property to the fullest extent of the law.</p>
<p>5.2 Restricted use: No part or parts of the Platform, or any of the Materials may be reproduced, reverse engineered, decompiled, disassembled, separated, altered, distributed, republished, displayed, broadcast, hyperlinked, mirrored, framed, transferred or transmitted in any manner or by any means or stored in an information retrieval system or installed on any server, system or equipment without our prior written permission or that of the relevant copyright owners. Subject to Clause 5.3, permission will only be granted to you to download, print or use the Materials for personal and non-commercial uses, provided that you do not modify the Materials and that we or the relevant copyright owners retain all copyright and other proprietary notices contained in the Materials.</p>
<p>5.3 Trademarks: The Trademarks shall have the meaning as set out in the attached schedule herein. Nothing on the Platform and in these Terms of Use shall be construed as granting, by implication, estoppel, or otherwise grant, any license or right to use (including as a meta tag or as a “hot” link to any other website) any Trademarks displayed on the Services, without our written permission or any other applicable trademark owner.</p>
<p>6. Our limitation of responsibility and liability</p>
<p>6.1 No representations or warranties: The Services, the Platform and the Materials are provided on an “as is” and “as available” basis. All data and/or information contained in the Platform, the Services or the Materials are provided for informational purposes only. No representations or warranties of any kind, implied, express or statutory, including the warranties of non-infringement of third party rights, title, merchantability, satisfactory quality or fitness for a particular purpose, are given in conjunction with the Platform, the Services or the Materials. Without prejudice to the generality of the foregoing, we do not warrant:</p>
<p>(a) the accuracy, timeliness, adequacy, commercial value or completeness of all data and/or information contained in the Platform, the Services or the Materials;</p>
<p>(b) that the Platform, the Services or that any of the Materials will be provided uninterrupted, secure or free from errors or omissions, or that any identified defect will be corrected;</p>
<p>(c) that the Platform, the Services or the Materials are free from any computer virus or other malicious, destructive or corrupting code, agent, program or macros; and</p>
<p>(d) the security of any information transmitted by you or to you through the Platform or the Services, and you accept the risk that any information transmitted or received through the Services or the Platform may be accessed by unauthorised third parties and/or disclosed by us or our officers, employees or agents to third parties purporting to be you or purporting to act under your authority. Transmissions over the Internet and electronic mail may be subject to interruption, transmission blackout, delayed transmission due to internet traffic or incorrect data transmission due to the public nature of the Internet.</p>
<p>6.2 Exclusion of liability: Lazada Indemnitees shall not be liable to you for any Losses whatsoever or howsoever caused (regardless of the form of action) arising directly or indirectly in connection with:</p>
<p>(a) any access, use and/or inability to use the Platform or the Services;</p>
<p>(b) reliance on any data or information made available through the Platform and/or through the Services. You should not act on such data or information without first independently verifying its contents;</p>
<p>(c) any system, server or connection failure, error, omission, interruption, delay in transmission, computer virus or other malicious, destructive or corrupting code, agent program or macros; and</p>
<p>(d) any use of or access to any other website or webpage linked to the Platform, even if we or our officers or agents or employees may have been advised of, or otherwise might have anticipated, the possibility of the same.</p>
<p>6.3 At your own risk: Any risk of misunderstanding, error, damage, expense or Losses resulting from the use of the Platform is entirely at your own risk and we shall not be liable therefor.</p>
<p>7. Hyperlinks, alerts and advertising</p>
<p>7.1 Hyperlinks: For your convenience, we may include hyperlinks to other websites or content on the Internet that are owned or operated by third parties. Such linked websites or content are not under our control and we are not liable for any errors, omissions, delays, defamation, libel, slander, falsehood, obscenity, pornography, profanity, inaccuracy or any other objectionable material contained in the contents, or the consequences of accessing, any linked website. Any hyperlinks to any other websites or content are not an endorsement or verification of such websites or content and you agree that your access to or use of such linked websites or content is entirely at your own risk.</p>
<p>7.2 Advertising: We may attach banners, java applets and/or such other materials to the Platform for the purposes of advertising our or our Third Party Vendors’ products and/or services. For the avoidance of doubt, you shall not be entitled to receive any payment, fee and/or commission in respect of any such advertising or other promotional materials.</p>
<p>8. Your submissions and information</p>
<p>8.1 Submissions by you: You grant us a non-exclusive license to use the materials or information that you submit to the Platform and/or provide to us, including but not limited to, questions, reviews, comments, and suggestions (collectively, “Submissions”). When you post comments or reviews to the Platform, you also grant us the right to use the name that you submit or your Username in connection with such review, comment, or other content. You shall not use a false e-mail address, pretend to be someone other than yourself or otherwise mislead us or third parties as to the origin of any Submissions. We may, but shall not be obligated to, publish, remove or edit your Submissions.</p>
<p>8.2 Consent to receive e-mails: You consent to and authorise the use by us of any information provided by you (including Personal Data) for the purposes of sending informational and promotional e-mails to you. Your agreement to the provisions of this Clause 8.2 shall constitute your consent for the purpose of the provisions of any spam control laws (whether in Thailand or elsewhere). You may subsequently opt out of receiving promotional e-mails by clicking on the appropriate hyperlink in any promotional e-mail.</p>
<p>8.3 Privacy Policy: You acknowledge that you have read and agree to the Privacy Policy at https://www.lazada.co.th/privacy-policy/ and consent to our collection, use and disclosure of your Personal Data for the purposes as set out in the Privacy Policy.</p>
<p>9. Termination</p>
<p>9.1 Termination by us: In our sole and absolute discretion, we may with immediate effect and either with or without notice, terminate your use of the Platform and/or Services and/or disable your Username and Password. We may bar access to the Platform and/or Services (or any part thereof) for any reason whatsoever, including a breach of any of these Terms of Use or where if we believe that you have violated or acted inconsistently with any terms or conditions set out herein, or if in our opinion or the opinion of any regulatory authority, it is not suitable to continue providing the services relating to the Platform.</p>
<p>9.2 Termination by you: You may terminate these Terms of Use by giving seven (7) days’ advance notice in writing to us.</p>
<p>10. Notices</p>
<p>10.1 Notices from us: All notices or other communications given to you if:</p>
<p>(a) communicated through any print or electronic media as we may select will be deemed to be notified to you on the date of publication or broadcast; or</p>
<p>(b) sent by post or left at your last known address will be deemed to be received by you on the day following such posting or on the day when it was so left.</p>
<p>10.2 Notices from you: You may only give notice to us in writing sent to our designated address or e-mail address at Unit 2901, 29th floor Bhiraj Tower, 689 Sukhumvit Road, North Klongton Subdistrict, Vadhana District, Bangkok 10110 Thailand and www.lazada.co.th/contact, and we shall be deemed to have received such notice only upon receipt. While we endeavour to respond promptly to notices from you, we cannot guarantee that we will always respond with consistent speed.</p>
<p>10.3 Other modes: Notwithstanding Clauses 10.1 and 10.2, we may from time to time designate other acceptable modes of giving notices (including but not limited to e-mail or other forms of electronic communication) and the time or event by which such notice shall be deemed given.</p>
<p>11. General</p>
<p>11.1 Cumulative rights and remedies: Unless otherwise provided under these Terms of Use, the provisions of these Terms of Use and our rights and remedies under these Terms of Use are cumulative and are without prejudice and in addition to any rights or remedies we may have in law or in equity, and no exercise by us of any one right or remedy under these Terms of Use, or at law or in equity, shall (save to the extent, if any, provided expressly in these Terms of Use or at law or in equity) operate so as to hinder or prevent our exercise of any other such right or remedy as at law or in equity.</p>
<p>11.2 No waiver: Our failure to enforce these Terms of Use shall not constitute a waiver of these terms, and such failure shall not affect the right later to enforce these Terms of Use. We would still be entitled to use our rights and remedies in any other situation where you breach these Terms of Use.</p>
<p>11.3 Severability: If at any time any provision of these Terms of Use shall be or shall become illegal, invalid or unenforceable in any respect, the legality, validity and enforceability of the remaining provisions of this Agreement shall not be affected or impaired thereby, and shall continue in force as if such illegal, invalid or unenforceable provision was severed from these Terms of Use.</p>
<p>11.4 Rights of third parties: A person or entity who is not a party to these Terms of Use shall have no right under any legislation in any jurisdiction to enforce any term of these Terms of Use, regardless of whether such person or entity has been identified by name, as a member of a class or as answering a particular description. For the avoidance of doubt, nothing in this Clause shall affect the rights of any permitted assignee or transferee of these Terms of Use.</p>
<p>11.5 Governing law: Use of the Platform and/or the Services and these Terms of Use shall be governed by and construed in accordance with Thailand law and you hereby submit to the exclusive jurisdiction of the Courts of Thailand.</p>
<p>11.6 Injunctive relief: We may seek immediate injunctive relief if we make a good faith determination that a breach or non-performance is such that a temporary restraining order or other immediate injunctive relief is the only appropriate or adequate remedy.</p>
<p>11.7 Amendments: We may by notice through the Platform or by such other method of notification as we may designate (which may include notification by way of e-mail), vary the terms and conditions of these Terms of Use, such variation to take effect on the date we specify through the above means. If you use the Platform or the Services after such date, you are deemed to have accepted such variation. If you do not accept the variation, you must stop access or using the Platform and the Services and terminate these Terms of Use. Our right to vary these Terms of Use in the manner aforesaid will be exercised with may be exercised without the consent of any person or entity who is not a party to these Terms of Use.</p>
<p>11.8 Correction of errors: Any typographical, clerical or other error or omission in any acceptance, invoice or other document on our part shall be subject to correction without any liability on our part.</p>
<p>11.9 Currency: Money references under these Terms of Use shall be in Thailand Baht.</p>
<p>11.10 Language: In the event that these Terms of Use is executed or translated in any language other than English (“Foreign Language Version”), the English language version of these Terms of Use shall govern and shall take precedence over the Foreign Language Version.</p>
<p>11.11 Entire agreement: These Terms of Use shall constitute the entire agreement between you and us relating to the subject matter hereof and supersedes and replaces in full all prior understandings, communications and agreements with respect to the subject matter hereof.</p>
<p>11.12 Binding and conclusive: You acknowledge and agree that any records (including records of any telephone conversations relating to the Services, if any) maintained by us or our service providers relating to or in connection with the Platform and the Services shall be binding and conclusive on you for all purposes whatsoever and shall be conclusive evidence of any information and/or data transmitted between us and you. You hereby agree that all such records are admissible in evidence and that you shall not challenge or dispute the admissibility, reliability, accuracy or the authenticity of such records merely on the basis that such records are in electronic form or are the output of a computer system, and you hereby waive any of your rights, if any, to so object.</p>
<p>11.13 Sub-contracting and delegation: We reserve the right to delegate or sub-contract the performance of any of our functions in connection with the Platform and/or Services and reserve the right to use any service providers, subcontractors and/or agents on such terms as we deem appropriate.</p>
<p>11.14 Assignment: You may not assign your rights under these Terms of Use without our prior written consent. We may assign our rights under these Terms of Use to any third party.</p>
<p>11.15 Force Majeure: We shall not be liable for non-performance, error, interruption or delay in the performance of its obligations under these Terms of Use (or any part thereof) or for any inaccuracy, unreliability or unsuitability of the Platform's and/or Services’ contents if this is due, in whole or in part, directly or indirectly to an event or failure which is beyond our reasonable control.</p>
<p>Schedule 1</p>
<p>Definitions and Interpretation</p>
<p>1. Definitions. Unless the context otherwise requires, the following expressions shall have the following meanings in these Terms of Use:</p>
<p>1.1 “Customer” has the same meaning as in the Terms &amp; Conditions of Sale.</p>
<p>1.2 “Intellectual Property” means all copyright, patents, utility innovations, trademarks and service marks, geographical indications, domain names, layout design rights, registered designs, design rights, database rights, trade or business names, rights protecting trade secrets and confidential information, rights protecting goodwill and reputation, and all other similar or corresponding proprietary rights and all applications for the same, whether presently existing or created in the future, anywhere in the world, whether registered or not, and all benefits, privileges, rights to sue, recover damages and obtain relief or other remedies for any past, current or future infringement, misappropriation or violation of any of the foregoing rights.</p>
<p>1.3 “Lazada Indemnitees” means Lazada and all of its respective officers, employees, directors, agents, contractors and assigns.</p>
<p>1.4 “Lazada”, “we”, “our” and “us” refer to Lazada Ltd., a company incorporated pursuant to the laws of Thailand under registration number 0105555040244 and having its registered address at Unit 2901, 29th floor Bhiraj Tower, 689 Sukhumvit Road, North Klongton Subdistrict, Vadhana District, Bangkok 10110 Thailand.</p>
<p>1.5 “Listing Price” means the price of Products listed for sale to Customers, as stated on the Platform.</p>
<p>1.6 “Losses” means all penalties, losses, settlement sums, costs (including legal fees and expenses on a solicitor-client basis), charges, expenses, actions, proceedings, claims, demands and other liabilities, whether foreseeable or not.</p>
<p>1.7 “Materials” means, collectively, all web pages on the Platform, including the information, images, links, sounds, graphics, video, software, applications and other materials displayed or made available on the Platform and the functionalities or services provided on the Platform.</p>
<p>1.8 “Order” means your order for Products sent through the Platform in accordance with the Terms &amp; Conditions of Sale.</p>
<p>1.9 “Password” refers to the valid password that a Customer who has an account with Lazada may use in conjunction with the Username to access the relevant Platform and/or Services.</p>
<p>1.10 “Personal Data” means data, whether true or not, that can be used to identify, contact or locate you. Personal Data can include your name, e-mail address, billing address, shipping address, phone number and credit card information. Personal Data shall be deemed to include any data that you have provided to us when placing an Order, regardless of whether you have an account with us.</p>
<p>1.11 “Platform” means (a) both the web and mobile versions of the website operated and/or owned by Lazada and/or its affiliates which is presently located at www.lazada.co.th; and (b) the mobile applications made available from time to time by Lazada and/or its affiliates, including the iOS and Android versions.</p>
<p>1.12 “Privacy Policy” means the privacy policy set out at https://www.lazada.co.th/privacy-policy/.</p>
<p>1.13 “Product” means a product (including any installment of the product or any parts thereof) available for sale to Customers on the Platform.</p>
<p>1.14 “Prohibited Material” means any information, graphics, photographs, data and/or any other material that:</p>
<p>(a) contains any computer virus or other invasive or damaging code, program or macro;</p>
<p>(a) infringes any third-party Intellectual Property or any other proprietary rights;</p>
<p>(b) is defamatory, libelous or threatening;</p>
<p>(c) is obscene, pornographic, indecent, counterfeited, fraudulent, stolen, harmful or otherwise illegal under the applicable law; and/or</p>
<p>(d) is or may be construed as offensive and/or otherwise objectionable, in our sole opinion.</p>
<p>1.15 “Services” means services, information and functions made available by us and/or its affiliates on the Platform.</p>
<p>1.16 “Submission” is as defined in Clause 8.1 of these Terms of Use.</p>
<p>1.17 “Terms &amp; Conditions of Sale” means the terms and conditions governing a Customer’s purchase of the Products and are set out at https://www.lazada.co.th/terms-conditions/.</p>
<p>1.18 “Terms of Use” means the recitals, Clauses 1 to 11 and any Schedules to these terms and conditions.</p>
<p>1.19 “Trademarks” means the trademarks, service marks, trade names and logos used and displayed on the Platform, whether registered or unregistered, and owned by Lazada or any third party.</p>
<p>1.20 “Username” refers to the unique login identification name or code which identifies a Customer who has an account with Lazada.</p>
<p data-spm-anchor-id="a2o4m.tm80185656.4889704610.i1.4f46B9uRB9uRG4">1.21 “Voucher” means a voucher for credit which may be used by a Customer, subject to Voucher Terms &amp; Conditions and other terms and conditions, towards the payment of purchases on the Platform.</p>
<p>1.22 “Voucher Terms &amp; Conditions” are set out at http://www.lazada.co.th/terms-conditions/#voucher.</p>
<p>1.23 “you” and “your” refer to the individuals over the age of 20 or otherwise under the supervision of a parent or legal guardian.</p>
<p>2. Interpretation: Any reference in these Terms of Use to any provision of a statute shall be construed as a reference to that provision as amended, re-enacted or extended at the relevant time. In the Agreement, whenever the words “include”, “includes” or “including” are used, they will be deemed to be followed by the words “without limitation”. Unless expressly indicated otherwise, all references to a number of days mean calendar days, and the words “month” or “monthly” as well as all references to a number of months means calendar months. Clause headings are inserted for convenience only and shall not affect the interpretation of these Terms of Use. In the event of a conflict or inconsistency between any two or more provisions under these Terms of Use, whether such provisions are contained in the same or different documents, such conflict or inconsistency shall be resolved in favor of Lazada and the provision which is more favorable to Lazada shall prevail.</p>
<p><a href="https://pages.lazada.co.th/wow/gcp/route/lazada/th/upr_1000345_lazada/channel/th/upr-router/th?hybrid=1&amp;data_prefetch=true&amp;prefetch_replace=1&amp;at_iframe=1&amp;wh_pid=/lazada/channel/th/central/TermsandConditions" target="_blank">BACK TO MAIN PAGE</a>&nbsp;</p>
<p></p></div></div></div>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>

</style>